Repository kintoproj/kinto-core, pull requests merged in 2021-02, with the labels that each got.

#11 🚧 Add github actions automation to build/test/push the image
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/push_to_registry.yml
Labels: documentation

#13 🐛 Remove last mentions of KintoKubeCore
  cmd/app/main.go
  internal/server/kintokubecoreservice.go
  internal/server/mock/mock.go
  pkg/types/coreapi.pb.go
  pkg/types/models.pb.go
  pkg/types/workflowapi.pb.go
  proto/README.md
  proto/coreapi.proto
Labels: bug

#12 🌟 feat: add apache 2.0 LICENSE
  LICENSE
Labels: documentation

#15 📃 Improve README with more information.
  README.md
  internal/config/config.go
Labels: documentation

#23 🚧 Add option to disable SSL
  .env-example
  README.md
  internal/config/config.go
  internal/store/kube/chisel.go
  internal/store/kube/ingress.go
  internal/store/kube/kube.go
  internal/store/kube/kube_test.go
Labels: enhancement
